Sprint 3
iliya132/middle.messenger.praktikum.yandex pull request #9
Opened 2022-01-16 11:28 UTC by iliya132

2022-01-16 14:47 UTC, DmitryKhitrin requested changes
Спасибо за вашу работу, все выглядит очень не плохо. Но есть некоторые проблемы которые хотелось бы поправить:

- переход по несуществующему урлу, отдает системнуб страницу, а должна быть 404
- вообще любой переход кроме / для залогиненного пользователя отдает "Page no found"
- так же в комментариях указал, на что можно обратить внимание 
-

2022-01-16 14:47 UTC, DmitryKhitrin commented on src/controllers/authController.ts
> +    const answer: IUserApiReponse | string = await this.api.read()
Из за смешения async/await и обычной работы с Promise, код начал достаточно сложно читаться. В данном случае с использование await было бы проще написать вот так:

```
try {
    answer = await this.api.read();
    return {
       ...
    }

} catch (erorr) {
    return {
        error,
        isSignedIn: false,
        user: null,
     }
}
```

2022-01-16 14:47 UTC, DmitryKhitrin commented on src/pages/register/register.ts
> +  handleSubmit() {
Для приватных функций есть ключевое слово private

2022-01-17 06:42 UTC, iliya132 commented
@DmitryKhitrin Ревью поправил. Касательно "`вообще любой переход кроме / для залогиненного пользователя отдает "Page no found"`" это скорее ошибка не приложения, а встроенный роутинг в netlify. Добавил в build config редирект. Теперь там все работает. Почему то на сайте Я.практикума подзависло ревью. Сможете протолкнуть?

2022-01-18 06:33 UTC, DmitryKhitrin approved these changes
Супер!) Спасибо за внесенные правки и удачи в следующем спринте!)

2022-01-18 08:04 UTC, merged